# Generated by Django 4.0.4 on 2022-04-28 20:42

import django.contrib.postgres.constraints
import django.contrib.postgres.fields.ranges
from django.db import migrations, models

import pg_bitemporal.django.base


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                ("order_id", models.UUIDField()),
                ("row_id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "app_period",
                    django.contrib.postgres.fields.ranges.DateTimeRangeField(
                        default=pg_bitemporal.django.base.default_range
                    ),
                ),
                (
                    "txn_period",
                    django.contrib.postgres.fields.ranges.DateTimeRangeField(
                        default=pg_bitemporal.django.base.default_range
                    ),
                ),
            ],
            options={
                "db_table": "order",
            },
        ),
        migrations.CreateModel(
            name="OrderHistory",
            fields=[
                ("order_id", models.UUIDField()),
                ("row_id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "app_period",
                    django.contrib.postgres.fields.ranges.DateTimeRangeField(
                        default=pg_bitemporal.django.base.default_range
                    ),
                ),
                (
                    "txn_period",
                    django.contrib.postgres.fields.ranges.DateTimeRangeField(
                        default=pg_bitemporal.django.base.default_range
                    ),
                ),
            ],
            options={
                "db_table": "order_history",
            },
        ),
        migrations.AddConstraint(
            model_name="orderhistory",
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(
                expressions=[("order_id", "="), ("app_period", "&&")],
                name="order_history_bitemporal_key_exclusion",
            ),
        ),
        migrations.AddConstraint(
            model_name="orderhistory",
            constraint=models.UniqueConstraint(
                fields=("row_id", "txn_period"),
                name="order_history_composite_key",
            ),
        ),
        migrations.AddConstraint(
            model_name="order",
            constraint=models.UniqueConstraint(
                fields=("app_period", "order_id"),
                name="order_bitemporal_unique_key",
            ),
        ),
        migrations.AddConstraint(
            model_name="order",
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(
                expressions=[("order_id", "="), ("app_period", "&&")],
                name="order_bitemporal_key_exclusion",
            ),
        ),
    ]
